### ISSUE TITLE
Make "add bookmark" option appear in the landing page.

### ISSUE THREAD

**Issue by sahaja2000** [sahaja2000/bookmarks-manager#1]
Since we are building a bookmarks manager, it would be better if users could see "add bookmark" option as soon as they open the site without wasting their time to figure out where they can add bookmarks. So please make "add bookmark" feature appear in the landing page rather than other pages. This will enhance user experience.

**Comment by ganesh720acharya** [comment]
Okay I will make the necessary changes and  I will push the  corrected code soon!!!

**Comment by ganesh720acharya** [comment]
It's good to overcome from this issue and I have successfully done it. So, without any delay I would like to push the file/code so that you guys can view it and perform further task.
Thank you!!!!!
