### ISSUE TITLE
"Go back" button not functioning in my bookmarks and category page.

### ISSUE THREAD

**Issue by sahaja2000** [sahaja2000/bookmarks-manager#5]
There is a "go back" button in my bookmarks and category page but it is not working. It seems like you forgot to give the link to navigate back to the home page. Please fix this.

**Comment by ganesh720acharya** [comment]
Thank you for feedback, I will figure it out and pushed the code.

**Comment by ganesh720acharya** [comment]
I have fixed those bugs and I have already pushed the file. Thank You!!
