### ISSUE TITLE
Uneven and improper spaces in my bookmarks page.

### ISSUE THREAD

**Issue by sahaja2000** [sahaja2000/bookmarks-manager#6]
My bookmarks list looks very congested with uneven and improper spaces. Please give proper spacing.
![Screenshot (279)](https://user-images.githubusercontent.com/78789861/118219445-352bf000-b499-11eb-83ae-5ef978d41c92.png)

**Comment by ganesh720acharya** [comment]
I will figure it out!!!

**Comment by ganesh720acharya** [comment]
I have fixed it out and I have pushed the file.
