### ISSUE TITLE
Low color contrast in login/signup page.

### ISSUE THREAD

**Issue by sahaja2000** [sahaja2000/bookmarks-manager#7]
Color contrast seems a little low in the buttons of login/signup page. Please pick a color with good contrast ratio.

**Comment by ganesh720acharya** [comment]
I will solve it and pushed the file again after solving

**Comment by ganesh720acharya** [comment]
I have solve it and already pushed the file.
Thank you

**Comment by sahaja2000** [comment]
Thank you! Seems okay now.
